# externalsecret.yaml — bc-migrate-service
# Pulls secrets from Vault via External Secrets Operator.
# Never commit real secret values — all secrets are managed in Vault.
# Vault path: secret/data/<licencePlate>-<environment>/bc-migrate-service

{{- if .Values.service.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bc-migrate-service.fullname" . }}-secrets
  labels:
    {{- include "bc-migrate-service.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store   # must match the ClusterSecretStore installed on the cluster
  target:
    name: {{ include "bc-migrate-service.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.service.externalSecrets.secretKeys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.service.externalSecrets.vaultPath }}
        property: {{ . }}
    {{- end }}
{{- end }}
