// src/services/uploader.ts
// Creates a GitHub Release and uploads the PDF + markdown as release assets.
//
// Uses the caller's GitHub token so the release appears under their credentials.
// Falls back to the App installation token if no caller token is available.

import { Octokit }  from '@octokit/rest'
import { readFile } from 'node:fs/promises'
import { basename } from 'node:path'

export interface UploadArtifactOptions {
  repo:         string   // owner/name
  pdfPath:      string
  markdownPath: string
  appName:      string
  callerToken:  string
}

export async function uploadArtifact(opts: UploadArtifactOptions): Promise<string> {
  const { repo, pdfPath, markdownPath, appName, callerToken } = opts

  const [owner, repoName] = repo.split('/')
  const octokit = new Octokit({ auth: callerToken })

  const tagName    = `migration-analysis-${new Date().toISOString().slice(0,10)}`
  const releaseName = `${appName} Migration Analysis — ${new Date().toLocaleDateString('en-CA')}`

  // Create or update a release
  let releaseId: number
  try {
    const { data } = await octokit.repos.createRelease({
      owner,
      repo: repoName,
      tag_name:    tagName,
      name:        releaseName,
      body:        'Migration analysis generated by @bc-migrate extension.',
      draft:       false,
      prerelease:  true,
    })
    releaseId = data.id
  } catch {
    // Release with that tag may already exist — get it
    const { data } = await octokit.repos.getReleaseByTag({ owner, repo: repoName, tag: tagName })
    releaseId = data.id
  }

  // Upload PDF
  const pdfBuffer = await readFile(pdfPath)
  const { data: pdfAsset } = await octokit.repos.uploadReleaseAsset({
    owner,
    repo:       repoName,
    release_id: releaseId,
    name:       basename(pdfPath),
    data:       pdfBuffer as unknown as string,
    headers:    { 'content-type': 'application/pdf' },
  })

  // Upload markdown
  const mdBuffer = await readFile(markdownPath, 'utf-8')
  await octokit.repos.uploadReleaseAsset({
    owner,
    repo:       repoName,
    release_id: releaseId,
    name:       basename(markdownPath),
    data:       mdBuffer,
    headers:    { 'content-type': 'text/markdown' },
  })

  return pdfAsset.browser_download_url
}
